import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import Header from "@/components/custom/Header";
import SplashCursor from "@/components/reactBits/SplashCursor";



const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], weight: ["400","600","700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.className} suppressHydrationWarning>
      
      <body>
        <Provider>
        <Header/>
      
        {children}

        </Provider>
      </body>
    </html>
  );
}
