// app/layout.js
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import Header from "@/components/custom/LandingPage/Header";
import { ConvexClientProvider } from "./ConvexClientProvider";

const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"], 
  weight: ["400", "600", "700"] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.className} suppressHydrationWarning>
      <body>
      <ConvexClientProvider>
        <Provider>
          <Header />
          {children}
        </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
